
language: node_js

node_js:
  - '10.0'

sudo: required

cache:
  directories:
  - corona-rebound-ui/node_modules

before_script:
  - npm install -g firebase-tools

script:
  - cd corona-rebound-ui
  - npm test
  - npm run build

deploy:
  skip_cleanup: true
  provider: script
  script: firebase deploy --token "$FIREBASE_TOKEN" --non-interactive
  on:
    branch: master
